/*
This is a function that returns an element with the text "from remote"
- generated by stenography 🤖
*/
export default {
    name: 'remote',
    render () {
      return <div>from remote</div>
    }
}