/*
The code is exporting a function called "render" which returns the string "from remote".
- generated by stenography 🤖
*/
export default {
    name: 'remote',
    render () {
      return <div>from remote</div>
    }
}