
/*
This is a function that redirects the user to another URL.
- generated by stenography 🤖
*/
func (a *App) redirectHandler(w http.ResponseWriter, r *http.Request) {
	var hash = mux.Vars(r)["hash"]

	if a.CacheOn {
		if cached := a.Aero.Get(hash); cached != "" {
			log.Println("Aerospike cache redirecting to", cached)
			http.Redirect(w, r, cached, http.StatusMovedPermanently)
			return
		}
	}

	u, err := a.UrlStore().Get(hash)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	} else if u.Id == 0 {
		http.NotFound(w, r)
		return
	}

	if a.CacheOn {
		a.Aero.Add(hash, u.Url)
	}

	log.Println(hash, "redirecting to", u.Url)
	http.Redirect(w, r, u.Url, http.StatusMovedPermanently)
}

/*
This is a function that takes an http.ResponseWriter and an http.Request, and it returns the status code of the response (in this case, StatusCreated).
- generated by stenography 🤖
*/
func (a *App) addHandler(w http.ResponseWriter, r *http.Request) {
	var inputUrl = r.FormValue("url")

	destUrl, err := parseUrl(inputUrl)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	u, err := a.UrlStore().GetByUrl(destUrl.String())
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	} else if u.Id != 0 {
		writeJson(w, http.StatusOK, u)
		return
	}

	u = Url{
		Hash: makeHash(destUrl.Host),
		Url:  destUrl.String(),
	}
	if err := a.UrlStore().Update(&u); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	log.Println(destUrl, "added")
	writeJson(w, http.StatusCreated, u)
}

/*
This function is checking if the hash in the URL matches a value that has been stored. If it does, then it will return an HTTP status of 200 and write JSON to the ResponseWriter with information about what was found.
- generated by stenography 🤖
*/
func (a *App) checkHandler(w http.ResponseWriter, r *http.Request) {
	var hash = r.FormValue("hash")

	u, err := a.UrlStore().Get(hash)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	} else if u.Id == 0 {
		http.NotFound(w, r)
		return
	}

	writeJson(w, http.StatusOK, u)
}

/*
This is a function that removes an item from the URL store.
- generated by stenography 🤖
*/
func (a *App) removeHandler(w http.ResponseWriter, r *http.Request) {
	var hash = r.FormValue("hash")

	if u, err := a.UrlStore().Get(hash); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	} else if u.Id == 0 {
		http.NotFound(w, r)
		return
	}

	err := a.UrlStore().Remove(hash)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	log.Println(hash, "removed")
	writeJson(w, http.StatusNoContent, nil)
}

/*
This function writes a JSON response to the http.ResponseWriter and returns true if it was successful, false otherwise.
- generated by stenography 🤖
*/
func writeJson(w http.ResponseWriter, status int, a interface{}) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(status)
	if a != nil {
		if err := json.NewEncoder(w).Encode(a); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
}