class AllStar:

    '''
    This code initializes a variable called self.mould_broke to false and sets the value of self.is_rockstar to False
    - generated by stenography 🤖
    '''
    def __init__(self):
        self.mould_broke = False
        self.is_rockstar = False

    '''
    The code is setting the variable "self.is_rockstar" to true, which means that the person will be a rock star now.
    - generated by stenography 🤖
    '''
    def become_rockstar(self):
        self.is_rockstar = True

    '''
    The function can_break_mould() returns True if the user is a rockstar.
    - generated by stenography 🤖
    '''
    def can_break_mould(self):
        return self.is_rockstar